### ISSUE TITLE
EventSource is not working in android

### ISSUE THREAD

**Issue by tmirun** [NepeinAV/react-sse-hooks#1]
hi @NepeinAV,
I am testing the library rc-eventsource-reborn.

it is not working in android device. including comment these lines.

did it work for you?

``` java
// try to comment this code
      ________________________
      NetworkingModule.setCustomClientBuilder(
        new NetworkingModule.CustomClientBuilder() {
          @Override
          public void apply(OkHttpClient.Builder builder) {
            builder.addNetworkInterceptor(new     FlipperOkhttpInterceptor(networkFlipperPlugin));
          }
        }
      );
      _______________________
```

**Comment by NepeinAV** [comment]
Hey!
1. Is it working on iOS device or emulator?
2. Did you try to run your app in Release mode?
3. Did you try to handle errors? What type of errors did you see in console? What basically happens when you try to use EventSource?
4. Provide minimal example of how you are using this (including package.json)

**Comment by tmirun** [comment]
in ios and ios simulator works perfectly. the problem is in android, I was testing with debug mode (run yarn android in react-native 0.63), it's not working in real device and emulator

basically the problem is `onmessage` doesn't call. (in ios work 👍)

I am looking for why happen this problem, I found this issue in react native, I think event source polyfill doesn't work in android. and maybe the problem is related to the Networking module
https://github.com/facebook/react-native/issues/28835

**Comment by NepeinAV** [comment]
I'm just tried to create new RN app and it is working fine.

Try it by yourself - https://github.com/NepeinAV/SSETest.

**Comment by NepeinAV** [comment]
Initially SSE wasn't working, but after i comment that lines of code it starts successfully.

**Comment by tmirun** [comment]
thank you a lot for responding quickly.
I will try it now and tell you some thing

**Comment by tmirun** [comment]
very strange it working for your project.

So the problem will be with openhab sse channel 🤔

when I try to connect return this error
```
error Event {isTrusted: false}
```

ok, I will invest in this problem.

can you explain why we need to comment these lines? (I am not native programmer)

``` java
// try to comment this code
      ________________________
      NetworkingModule.setCustomClientBuilder(
        new NetworkingModule.CustomClientBuilder() {
          @Override
          public void apply(OkHttpClient.Builder builder) {
            builder.addNetworkInterceptor(new     FlipperOkhttpInterceptor(networkFlipperPlugin));
          }
        }
      );
      _______________________
```

Thank you

**Comment by NepeinAV** [comment]
So this is network interceptor that allows us to see network interaction in [Flipper](https://github.com/facebook/flipper) app. My app was working in release mode, but not in debug and only one difference between them was this interceptor.

This is not a right solution to solve this problem, but at least my app is working as needed right now.

**Comment by tmirun** [comment]
kk, I think this problem is something that should resolve by react-native team.

I am following this issue, https://github.com/facebook/react-native/issues/28835, hope RN team can do something to make SSE work in pure JS without a thirty party library.

also, I mentioned 'rn-eventsource-reborn' in it. 😂

Thank you a lot. hope the ppl use this library and make it popular  😉

**Comment by tmirun** [comment]
I will close this Issue
